export const LOAD_EEW2_DATA='LOAD_EEW2_DATA';
export const GET_EEW2RECORDS_SUCCESS='GET_EEW2RECORDS_SUCCESS';
export const GET_EEW2RECORDS_ERROR='GET_EEW2RECORDS_ERROR';
export const GET_EEW2PDF_SUCCESS='GET_EEW2PDF_SUCCESS';
export const GET_EEW2PDF_ERROR='GET_EEW2PDF_ERROR';
export const POST_GENERATE_OUTPUTS_SUCCESS='POST_GENERATE_OUTPUTS_SUCCESS';
export const POST_GENERATE_OUTPUTS_ERROR='POST_GENERATE_OUTPUTS_ERROR';
//
export const GET_COMPANY_FILE_SUCCESS = 'GET_COMPANY_FILE_SUCCESS';
export const GET_COMPANY_FILE_ERROR = 'GET_COMPANY_FILE_ERROR';
//
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';