export const LOAD_EEW2_DATA='LOAD_EEW2_DATA';
export const GET_EEW2RECORDS_SUCCESS='GET_EEW2RECORDS_SUCCESS';
export const GET_EEW2RECORDS_ERROR='GET_EEW2RECORDS_ERROR';
export const GET_EEW2PDF_SUCCESS='GET_EEW2PDF_SUCCESS';
export const GET_EEW2PDF_ERROR='GET_EEW2PDF_ERROR';
export const POST_GENERATE_OUTPUTS_SUCCESS='POST_GENERATE_OUTPUTS_SUCCESS';
export const POST_GENERATE_OUTPUTS_ERROR='POST_GENERATE_OUTPUTS_ERROR';
export const POST_PUBUNPUB_OUTPUTS_SUCCESS='POST_PUBUNPUB_OUTPUTS_SUCCESS';
export const POST_PUBUNPUB_OUTPUTS_ERROR='POST_PUBUNPUB_OUTPUTS_ERROR';
export const POST_OUTPUTGEN_INPROGRESS_SUCCESS='POST_OUTPUTGEN_INPROGRESS_SUCCESS';
export const POST_OUTPUTGEN_INPROGRESS_ERROR='POST_OUTPUTGEN_INPROGRESS_ERROR';
export const LOAD_PDF_DATA='LOAD_PDF_DATA';
export const LOAD_COMP_DATA='LOAD_COMP_DATA';
export const GET_TRANSMITTER_SUCCESS='GET_TRANSMITTER_SUCCESS';
export const GET_TRANSMITTER_ERROR='GET_TRANSMITTER_ERROR';
export const GET_COMP_BY_TRANSMITTER_SUCCESS='GET_COMP_BY_TRANSMITTER_SUCCESS';
export const GET_COMP_BY_TRANSMITTER_ERROR='GET_COMP_BY_TRANSMITTER_ERROR';
export const GET_EMPLOYEES_SUCCESS='GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_ERROR='GET_EMPLOYEES_ERROR';
//
export const GET_COMPANY_FILE_SUCCESS = 'GET_COMPANY_FILE_SUCCESS';
export const GET_COMPANY_FILE_ERROR = 'GET_COMPANY_FILE_ERROR';
//
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_TEST_JNLP_SUCCESS='GET_TEST_JNLP_SUCCESS';
